### ISSUE TITLE
Great code.. will like to include visualization

### ISSUE THREAD

**Issue by 007ekho** [Snowflake-Labs/sfguide-frosty-llm-chatbot-on-streamlit-snowflake#25]
@sfc-gh-jcarroll  what do you think is the best way to prompt the llm to produce visualization without losing its core functions and also to prevent it from displaying the SQL code to the user? Thanks.

**Comment by sfc-gh-jcarroll** [comment]
Hey, it's outside the scope of this repository to generate visualization code like that. You probably want to use multiple prompts / LLM calls or some kind of agent framework already tuned to that task. You could remove the sql from the response in code if you don't want to display it using the same regex currently in place to extract and run it.
